import React from 'react';
import { Ionicons, MaterialIcons, MaterialCommunityIcons, FontAwesome5 } from '@expo/vector-icons';

// Modern icon component using Expo Vector Icons
const Icon = ({ name, size = 24, color = '#000', library = 'ionicons' }) => {
  const iconMap = {
    // Navigation icons
    'home': { lib: 'ionicons', name: 'home' },
    'home-outline': { lib: 'ionicons', name: 'home-outline' },
    'calendar': { lib: 'ionicons', name: 'calendar' },
    'calendar-outline': { lib: 'ionicons', name: 'calendar-outline' },
    'people': { lib: 'ionicons', name: 'people' },
    'people-outline': { lib: 'ionicons', name: 'people-outline' },
    'information-circle': { lib: 'ionicons', name: 'information-circle' },
    'information-circle-outline': { lib: 'ionicons', name: 'information-circle-outline' },
    'call': { lib: 'ionicons', name: 'call' },
    'call-outline': { lib: 'ionicons', name: 'call-outline' },
    
    // Contact icons
    'person': { lib: 'ionicons', name: 'person' },
    'person-outline': { lib: 'ionicons', name: 'person-outline' },
    'person-circle-outline': { lib: 'ionicons', name: 'person-circle-outline' },
    'mail': { lib: 'ionicons', name: 'mail' },
    'mail-outline': { lib: 'ionicons', name: 'mail-outline' },
    'location': { lib: 'ionicons', name: 'location' },
    'location-outline': { lib: 'ionicons', name: 'location-outline' },
    'globe': { lib: 'ionicons', name: 'globe' },
    'globe-outline': { lib: 'ionicons', name: 'globe-outline' },
    'business': { lib: 'ionicons', name: 'business' },
    'business-outline': { lib: 'ionicons', name: 'business-outline' },
    
    // Activity icons
    'heart': { lib: 'ionicons', name: 'heart' },
    'heart-outline': { lib: 'ionicons', name: 'heart-outline' },
    'map': { lib: 'ionicons', name: 'map' },
    'map-outline': { lib: 'ionicons', name: 'map-outline' },
    'snow': { lib: 'material', name: 'ac-unit' },
    'leaf': { lib: 'material', name: 'eco' },
    'walk': { lib: 'material', name: 'directions-walk' },
    'walk-outline': { lib: 'material', name: 'directions-walk' },
    'footsteps': { lib: 'ionicons', name: 'footsteps' },
    'footsteps-outline': { lib: 'ionicons', name: 'footsteps-outline' },
    'trail-sign': { lib: 'materialcommunity', name: 'sign-direction' },
    'trail-sign-outline': { lib: 'materialcommunity', name: 'sign-direction' },
    'trending-up': { lib: 'ionicons', name: 'trending-up' },
    'trending-up-outline': { lib: 'ionicons', name: 'trending-up-outline' },
    'rainy': { lib: 'ionicons', name: 'rainy' },
    'rainy-outline': { lib: 'ionicons', name: 'rainy-outline' },
    'thunderstorm': { lib: 'ionicons', name: 'thunderstorm' },
    'thunderstorm-outline': { lib: 'ionicons', name: 'thunderstorm-outline' },
    'cloudy': { lib: 'ionicons', name: 'cloudy' },
    'cloudy-outline': { lib: 'ionicons', name: 'cloudy-outline' },
    'partly-sunny': { lib: 'ionicons', name: 'partly-sunny' },
    'partly-sunny-outline': { lib: 'ionicons', name: 'partly-sunny-outline' },
    'barbell': { lib: 'ionicons', name: 'barbell' },
    'barbell-outline': { lib: 'ionicons', name: 'barbell-outline' },
    'skull': { lib: 'ionicons', name: 'skull' },
    'skull-outline': { lib: 'ionicons', name: 'skull-outline' },
    'grid': { lib: 'ionicons', name: 'grid' },
    'grid-outline': { lib: 'ionicons', name: 'grid-outline' },
    'pie-chart': { lib: 'ionicons', name: 'pie-chart' },
    'pie-chart-outline': { lib: 'ionicons', name: 'pie-chart-outline' },
    'medal': { lib: 'ionicons', name: 'medal' },
    'medal-outline': { lib: 'ionicons', name: 'medal-outline' },
    'diamond': { lib: 'ionicons', name: 'diamond' },
    'diamond-outline': { lib: 'ionicons', name: 'diamond-outline' },
    'planet': { lib: 'ionicons', name: 'planet' },
    'planet-outline': { lib: 'ionicons', name: 'planet-outline' },
    'infinite': { lib: 'ionicons', name: 'infinite' },
    'infinite-outline': { lib: 'ionicons', name: 'infinite-outline' },
    'sparkles': { lib: 'ionicons', name: 'sparkles' },
    'sparkles-outline': { lib: 'ionicons', name: 'sparkles-outline' },
    'mountain': { lib: 'materialcommunity', name: 'image-filter-hdr' },
    'arrow-up-circle': { lib: 'ionicons', name: 'arrow-up-circle' },
    'arrow-up-circle-outline': { lib: 'ionicons', name: 'arrow-up-circle-outline' },
    'apps': { lib: 'ionicons', name: 'apps' },
    'apps-outline': { lib: 'ionicons', name: 'apps-outline' },
    'trophy': { lib: 'ionicons', name: 'trophy' },
    'trophy-outline': { lib: 'ionicons', name: 'trophy-outline' },
    'time': { lib: 'ionicons', name: 'time' },
    'time-outline': { lib: 'ionicons', name: 'time-outline' },
    'book': { lib: 'ionicons', name: 'book' },
    'book-outline': { lib: 'ionicons', name: 'book-outline' },
    'flame': { lib: 'ionicons', name: 'flame' },
    'flame-outline': { lib: 'ionicons', name: 'flame-outline' },
    'stats-chart': { lib: 'ionicons', name: 'stats-chart' },
    'stats-chart-outline': { lib: 'ionicons', name: 'stats-chart-outline' },
    'fitness': { lib: 'ionicons', name: 'fitness' },
    'fitness-outline': { lib: 'ionicons', name: 'fitness-outline' },
    'bulb': { lib: 'ionicons', name: 'bulb' },
    'bulb-outline': { lib: 'ionicons', name: 'bulb-outline' },
    'flash': { lib: 'ionicons', name: 'flash' },
    'flash-outline': { lib: 'ionicons', name: 'flash-outline' },
    'add-circle': { lib: 'ionicons', name: 'add-circle' },
    'add-circle-outline': { lib: 'ionicons', name: 'add-circle-outline' },
    'add': { lib: 'ionicons', name: 'add' },
    'close': { lib: 'ionicons', name: 'close' },
    'trash': { lib: 'ionicons', name: 'trash' },
    'trash-outline': { lib: 'ionicons', name: 'trash-outline' },
    'shield': { lib: 'ionicons', name: 'shield' },
    'shield-outline': { lib: 'ionicons', name: 'shield-outline' },
    'school': { lib: 'ionicons', name: 'school' },
    'school-outline': { lib: 'ionicons', name: 'school-outline' },
    'ellipse': { lib: 'ionicons', name: 'ellipse' },
    'ellipse-outline': { lib: 'ionicons', name: 'ellipse-outline' },
    'leaf-outline': { lib: 'ionicons', name: 'leaf-outline' },
    'refresh': { lib: 'ionicons', name: 'refresh' },
    'refresh-outline': { lib: 'ionicons', name: 'refresh-outline' },
    'people-circle': { lib: 'ionicons', name: 'people-circle' },
    'people-circle-outline': { lib: 'ionicons', name: 'people-circle-outline' },
    'briefcase': { lib: 'ionicons', name: 'briefcase' },
    'briefcase-outline': { lib: 'ionicons', name: 'briefcase-outline' },
    
    // Other icons
    'backpack': { lib: 'materialcommunity', name: 'bag-personal' },
    'backpack-outline': { lib: 'materialcommunity', name: 'bag-personal-outline' },
    'bookmark': { lib: 'ionicons', name: 'bookmark' },
    'bookmark-outline': { lib: 'ionicons', name: 'bookmark-outline' },
    'camera': { lib: 'ionicons', name: 'camera' },
    'camera-outline': { lib: 'ionicons', name: 'camera-outline' },
    'cash': { lib: 'ionicons', name: 'cash' },
    'cash-outline': { lib: 'ionicons', name: 'cash-outline' },
    'chatbubble-ellipses': { lib: 'ionicons', name: 'chatbubble-ellipses' },
    'chatbubble-ellipses-outline': { lib: 'ionicons', name: 'chatbubble-ellipses-outline' },
    'chatbubbles': { lib: 'ionicons', name: 'chatbubbles' },
    'chatbubbles-outline': { lib: 'ionicons', name: 'chatbubbles-outline' },
    'checkmark-done': { lib: 'ionicons', name: 'checkmark-done' },
    'checkmark-done-outline': { lib: 'ionicons', name: 'checkmark-done-outline' },
    'create': { lib: 'ionicons', name: 'create' },
    'create-outline': { lib: 'ionicons', name: 'create-outline' },
    'expand': { lib: 'ionicons', name: 'expand' },
    'expand-outline': { lib: 'ionicons', name: 'expand-outline' },
    'lock-closed': { lib: 'ionicons', name: 'lock-closed' },
    'lock-closed-outline': { lib: 'ionicons', name: 'lock-closed-outline' },
    'log-out': { lib: 'ionicons', name: 'log-out' },
    'log-out-outline': { lib: 'ionicons', name: 'log-out-outline' },
    'newspaper': { lib: 'ionicons', name: 'newspaper' },
    'newspaper-outline': { lib: 'ionicons', name: 'newspaper-outline' },
    'open': { lib: 'ionicons', name: 'open' },
    'open-outline': { lib: 'ionicons', name: 'open-outline' },
    'person-circle': { lib: 'ionicons', name: 'person-circle' },
    'play': { lib: 'ionicons', name: 'play' },
    'play-outline': { lib: 'ionicons', name: 'play-outline' },
    'restaurant': { lib: 'ionicons', name: 'restaurant' },
    'restaurant-outline': { lib: 'ionicons', name: 'restaurant-outline' },
    'settings': { lib: 'ionicons', name: 'settings' },
    'settings-outline': { lib: 'ionicons', name: 'settings-outline' },
    'share-social': { lib: 'ionicons', name: 'share-social' },
    'share-social-outline': { lib: 'ionicons', name: 'share-social-outline' },
    'shirt': { lib: 'ionicons', name: 'shirt' },
    'shirt-outline': { lib: 'ionicons', name: 'shirt-outline' },
    'speedometer': { lib: 'ionicons', name: 'speedometer' },
    'speedometer-outline': { lib: 'ionicons', name: 'speedometer-outline' },
    'water': { lib: 'ionicons', name: 'water' },
    'water-outline': { lib: 'ionicons', name: 'water-outline' },
    'arrow-back': { lib: 'ionicons', name: 'arrow-back' },
    'arrow-back-outline': { lib: 'ionicons', name: 'arrow-back-outline' },
    'bed-outline': { lib: 'ionicons', name: 'bed-outline' },
    'card': { lib: 'ionicons', name: 'card' },
    'card-outline': { lib: 'ionicons', name: 'card-outline' },
    'phone-portrait': { lib: 'ionicons', name: 'phone-portrait' },
    'phone-portrait-outline': { lib: 'ionicons', name: 'phone-portrait-outline' },
    'logo-facebook': { lib: 'ionicons', name: 'logo-facebook' },
    'medical': { lib: 'ionicons', name: 'medical' },
    'medical-outline': { lib: 'ionicons', name: 'medical-outline' },
    'chevron-forward': { lib: 'ionicons', name: 'chevron-forward' },
    'chevron-forward-outline': { lib: 'ionicons', name: 'chevron-forward' },
    'checkmark': { lib: 'ionicons', name: 'checkmark' },
    'checkmark-outline': { lib: 'ionicons', name: 'checkmark-outline' },
    'checkmark-circle': { lib: 'ionicons', name: 'checkmark-circle' },
    'checkmark-circle-outline': { lib: 'ionicons', name: 'checkmark-circle-outline' },
    'person-add': { lib: 'ionicons', name: 'person-add' },
    'person-add-outline': { lib: 'ionicons', name: 'person-add-outline' },
    'arrow-forward': { lib: 'ionicons', name: 'arrow-forward' },
    'close-circle': { lib: 'ionicons', name: 'close-circle' },
    'close-circle-outline': { lib: 'ionicons', name: 'close-circle-outline' },
    'star': { lib: 'ionicons', name: 'star' },
    'star-outline': { lib: 'ionicons', name: 'star-outline' },
    'book-open': { lib: 'ionicons', name: 'book' },
    'flag': { lib: 'ionicons', name: 'flag' },
    'flag-outline': { lib: 'ionicons', name: 'flag-outline' },
    'sunny': { lib: 'ionicons', name: 'sunny' },
    'sunny-outline': { lib: 'ionicons', name: 'sunny-outline' },
    'moon': { lib: 'ionicons', name: 'moon' },
    'moon-outline': { lib: 'ionicons', name: 'moon-outline' },
    'paw': { lib: 'materialcommunity', name: 'paw' },
    'bed': { lib: 'material', name: 'hotel' },
    
    // Contact detail icons
    'ribbon': { lib: 'ionicons', name: 'ribbon' },
    'ribbon-outline': { lib: 'ionicons', name: 'ribbon-outline' },
    'chatbubble': { lib: 'ionicons', name: 'chatbubble' },
    'chatbubble-outline': { lib: 'ionicons', name: 'chatbubble-outline' },
    'resize': { lib: 'ionicons', name: 'resize' },
    'resize-outline': { lib: 'ionicons', name: 'resize-outline' },
    'compass': { lib: 'ionicons', name: 'compass' },
    'compass-outline': { lib: 'ionicons', name: 'compass-outline' },
    'shield-checkmark': { lib: 'ionicons', name: 'shield-checkmark' },
    'shield-checkmark-outline': { lib: 'ionicons', name: 'shield-checkmark-outline' },
    'qr-code': { lib: 'ionicons', name: 'qr-code' },
    'qr-code-outline': { lib: 'ionicons', name: 'qr-code-outline' },
    'warning': { lib: 'ionicons', name: 'warning' },
    'warning-outline': { lib: 'ionicons', name: 'warning-outline' },
    'scan': { lib: 'ionicons', name: 'scan' },
    'scan-outline': { lib: 'ionicons', name: 'scan-outline' },
    'keypad': { lib: 'ionicons', name: 'keypad' },
    'keypad-outline': { lib: 'ionicons', name: 'keypad-outline' },
    'search': { lib: 'ionicons', name: 'search' },
    'search-outline': { lib: 'ionicons', name: 'search-outline' },
    'alert-circle': { lib: 'ionicons', name: 'alert-circle' },
    'alert-circle-outline': { lib: 'ionicons', name: 'alert-circle-outline' },
    'share-outline': { lib: 'ionicons', name: 'share-outline' },
    'camera-off': { lib: 'materialcommunity', name: 'camera-off' },
  };

  const iconConfig = iconMap[name] || { lib: 'ionicons', name: 'help-circle-outline' };
  const iconLib = iconConfig.lib || library;

  if (iconLib === 'ionicons') {
    return <Ionicons name={iconConfig.name} size={size} color={color} />;
  } else if (iconLib === 'material') {
    return <MaterialIcons name={iconConfig.name} size={size} color={color} />;
  } else if (iconLib === 'materialcommunity') {
    return <MaterialCommunityIcons name={iconConfig.name} size={size} color={color} />;
  } else if (iconLib === 'fontawesome5') {
    return <FontAwesome5 name={iconConfig.name} size={size} color={color} />;
  }

  return <Ionicons name="help-circle-outline" size={size} color={color} />;
};

export default Icon;

